function schema = lookupSchema()
    schema = struct( ...
        'sys', 'struct', ...
        'systype', 'char', ...
        'opt_params', 'struct', ...
        'config', 'struct', ...
        'dims', 'struct', ...
        'IO_params', 'struct', ...
        'T_sim', 'numeric', ...
        'data_options', 'struct', ...
        'T_d', 'numeric', ...
        'uncertainty_options', 'struct' ...
    );
end
